### ISSUE TITLE
Edit resource meta fails

### ISSUE THREAD

**Issue by t-book** [qld-gov-au/ckanext-resource-type-validation#16]
Hi, 
thanks for this great plugin.

I'm facing the following problem (ckan 2.9). The uploading works as expected. However, whenever I like to update the resource metadata (for example the description) an Exception is thrown. My guess/hope is this is a configuration issue?

Thanks for any hints!

![Bildschirmfoto 2022-01-07 um 22 50 42](https://user-images.githubusercontent.com/20478652/148612367-c29c46f9-c44d-4f39-8eed-b3d228cf0df9.png)

**Comment by duttonw** [comment]
Hi @t-book ,

Thanks for raising this issue and confirming that it is 'mostly' working on 2.9 we are still in the process of getting all of our plugins we use on opendata and publications 28 and 2.9 compatiable. 

As to your issue, this will need to add your example file here https://github.com/qld-gov-au/ckanext-resource-type-validation/tree/main/test/resources then add it to be tested add here https://github.com/qld-gov-au/ckanext-resource-type-validation/blob/main/ckanext/resource_type_validation/test_mime_type_validation.py#L47 and this file https://github.com/qld-gov-au/ckanext-resource-type-validation/blob/main/ckanext/resource_type_validation/resources/resource_types.json#L22 updated to include the magic mime time override "application/x-empty", ["image/png"]

**Comment by t-book** [comment]
@duttonw thanks a lot for your reply! Just to be sure I do understand you correctly.  

> As to your issue, this will need to add your example file here

You ask to provide the file in question as a PR, right?  I'd love to create a PR as you outlined above for further testing. 

The thing is, this is only a regular png (https://e1.pcloud.link/publink/show?code=XZWIeFZAMrnN2ikSpJslBdJHoOTGzKSAL7k), _that works nicely on create/upload_. 
However, _when editing_ the resource it looks like the ckan form sends some multipart form data that does not match with the allowed mime types (?!).


```
Content-Type | multipart/form-data; boundary=---------------------------2024016392649499141907502060
-- | --


-----------------------------2024016392649499141907502060
Content-Disposition: form-data; name="id"

69ccc832-aeef-4953-a577-f2120904474e
-----------------------------2024016392649499141907502060
Content-Disposition: form-data; name="url"

bildschirmfoto-2022-01-06-um-22.10.37.png
-----------------------------2024016392649499141907502060
Content-Disposition: form-data; name="upload"; filename=""
Content-Type: application/octet-stream


-----------------------------2024016392649499141907502060
Content-Disposition: form-data; name="clear_upload"


-----------------------------2024016392649499141907502060
Content-Disposition: form-data; name="name"

ABC
-----------------------------2024016392649499141907502060
Content-Disposition: form-data; name="description"

Test LLL
-----------------------------2024016392649499141907502060
Content-Disposition: form-data; name="format"

PNG
-----------------------------2024016392649499141907502060
Content-Disposition: form-data; name="save"

go-metadata
-----------------------------2024016392649499141907502060--
```

That is strange as `Content-Type: application/octet-stream` should be caught by:

```
    "allowed_overrides": {
        "application/octet-stream": ["*"],
```

?

Sorry, If I might complicate things. If you confirm that I should PR I will do it right away ;)

best regards,

Toni

**Comment by t-book** [comment]
Update: I think you meant to test it locally as described here: https://github.com/qld-gov-au/ckanext-resource-type-validation#testing ;)

**Comment by duttonw** [comment]
Hi @t-book , see https://github.com/qld-gov-au/ckanext-resource-type-validation/commit/6aceb64f1e516b56483449dc5e9450637e43b5ff  where i added the png test and it is passing.

After looking a bit deeper, I notice that the type encoding of application/empty means 0 bytes were sent in.

I do know that in ckan if a validation error occurs in a field on a resource being uploaded that the underlying uploaded document is lost even if the ui says its attached.  In opendata/publications when this occurs we 'clear' the upload so that it needs to be reselected. This is not an issue for url linked png. 

note that if your link to a website that does 'are you human checks' it may not give you the file you want on your inclusion (this is for archiver plugin etc)

**Comment by t-book** [comment]
Thanks again @duttonw  I now understand what is happening.

when you upload a document the form data of the file field looks like:

```
Content-Disposition: form-data; name="upload"; filename="Bildschirmfoto 2022-01-10 um 09.15.34.png"
Content-Type: image/png

PNG


IHDR²­
```

When we edit the same resource f.e. add a description the file field  is empty (as the image is there already):

```
Content-Disposition: form-data; name="upload"; filename=""
Content-Type: application/octet-stream
```

This fails because of validation.

> In opendata/publications when this occurs we 'clear' the upload so that it needs to be reselected. This is not an issue for url linked png.

I can confirm this workaround works. However, it might not be always possible. For example, if some editor does not have the image in question but only needs to update the description (downloading it first sounds a bit laborious).

I will see if we can change it to our needs. In case it looks useful I will share it here. 

Thanks!
